# Generated by Django 4.2 on 2023-04-11 15:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 4, 11, 15, 58, 45, 901917, tzinfo=datetime.timezone.utc), verbose_name='birthday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='mohammad', max_length=150, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='09904751095', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '09000000000'. Up to 11 digits allowed.", regex='(09\\d{9})')], verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1, verbose_name='sex'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name='username'),
        ),
    ]
